# Generated by Django 2.0.5 on 2018-07-05 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraudit', '0007_typo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('organisation', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='failedloginlog',
            name='forwarded_by',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='failedloginlog',
            name='ip_address',
            field=models.CharField(blank=True, max_length=40, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='failedloginlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='failedloginlog',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='forwarded_by',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='ip_address',
            field=models.CharField(blank=True, max_length=40, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userdeactivation',
            name='reason',
            field=models.CharField(blank=True, choices=[('AE', 'Account expired'), ('PE', 'Password expired'), ('FL', 'Too many failed login attempts')], max_length=2),
        ),
        migrations.AddField(
            model_name='failedloginlog',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='useraudit.LoginPlace'),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='useraudit.LoginPlace'),
        ),
    ]
